// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhsegvlsevdggfbzqvvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oc2VndmxzZXZkZ2dmYnpxdnZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2NzI3NTIsImV4cCI6MjA5MzI0ODc1Mn0.UQ_Pe9TGSkzaRMRMp95eDma4KKeqoWvBeaCSNR1BYoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);